### PR TITLE
Make it work in python-2.6 and python-3.2; remove interval=

### PR DESCRIPTION
**Pull request by ZyX-I**
`interval` setting was moved into configuration in Lokaltog/powerline#398.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
You should not do ans.encode('utf-8'). In python 2.x if ans is already a byte string that will cause it to first be decoded using the default encoding (ascii) and then re-encoded. This will raise a UnicodeDecodeError if ans contains any non-ascii characters. If you are trying to make it work in python 3.2, do this instead

``` python
if not isinstance(ans, bytes) and hasattr(ans, 'encode'):
   ans = ans.encode('utf-8')
```

Also when detecting system locale, you should add

``` python
if encoding.lower() == 'ascii':
   encoding = 'utf-8'
```

There are many older linux systems where python detects system encoding as ascii, but that actually use utf-8.

**Comment by ZyX-I** [comment]
> In python 2.x if ans is already a byte string that will cause it to first be decoded using the default encoding (ascii) and then re-encoded.

Rendering result is always unicode, `str(e)` also won’t emit a bytestring. Thus I am using EAFP principle for this job and not checking for bytestrings.

**Comment by kovidgoyal** [comment]
> > In python 2.x if ans is already a byte string that will cause it to first be decoded using the default encoding (ascii) and then re-encoded.
> 
> Rendering result is always unicode, `str(e)` also won’t emit a bytestring. Thus I am using EAFP principle for this job and not checking for bytestrings.

You know the rendering result is unicode _now_, there's no guarantee that
will always be true. Bugs happen, other people contribute to code,
things get changed that have side-effects. There's no reason to make this code
fragile when making it robust is so easy.

**Comment by ZyX-I** [comment]
> You know the rendering result is unicode _now_, there's no guarantee that
> will always be true. Bugs happen, other people contribute to code,
> things get changed that have side-effects. There's no reason to make this code
> fragile when making it robust is so easy.

We already placed much effort into having this result be _always_ unicode. To make it return `bytes` object big changes to `theme.py` and `renderer.py` are needed, they are hard to pass unnoticed. Or some hackery with objects having `__add__` and `__radd__` methods, much more complicated then I have in `bindings/ipython/pre_0_11.py`. This variant is not fragile for this reason. It avoids unnecessary second hash lookup and also makes it easy (done in most recent commit) to attach a handler for encoding error.

**Comment by ZyX-I** [comment]
Not done: `str()` is `unicode()` in python 3.

**Comment by ZyX-I** [comment]
Fixed your problem with `safe_bytes` (see comment in the function), squashed all intermediate commits containing bugs.

**Pull request merged**
