### PR TITLE
Add a silent option

### PR DESCRIPTION
**Pull request by hanwentao**
We can use 'powerline-daemon -s' in files like .bashrc to start daemon
automatically.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Do you really want the overhead of starting the python interpreter and then checking for a running daemon every time you launch an interactive shell?

Why not just add some code to launch the daemon to your env statrup scripts -- the same scripts sued to launch the gpg and ssh agents?

**Comment by hanwentao** [comment]
What file do you mean in Linux?

**Comment by kovidgoyal** [comment]
It depends on your distro and desktop environment. For example, with KDE on Gentoo it is /etc/kde/startup/agent-startup.sh.

If you are using a plain X session, it is ~/.xinitrc or ~/.startx or so on. Just grep /etc and your home directory for ssh-agent

**Comment by hanwentao** [comment]
I see.  However, I still think this silent option makes it complete :)

**Pull request merged**
